# Markdownlint configuration

# MD013 - Line length
MD013:
  line_length: 100
  code_blocks: false      # Don't check line length in code blocks
  tables: false           # Don't check line length in tables
  headings: false         # Don't check line length in headings
